config:
  ignore:
    - "README.md"
    - ".ticonfig.yaml"
    - "**/Dockerfile*"
    - "Jenkinsfile"
    - "**/*.md"
    - "**/*.py"
    - "**/*.txt"
    - "**/*.yml"
    - "**/*.yaml"
    - "Makefile"
    - "Rakefile"
    - "**/*.go"
    - "go.mod"
    - "go.sum"
    - "Vagrantfile"
    - "**/*.gemspec"
    - "**/*.nix"
    - "**/*.sh"
    - "go.mod"
    - "go.sum"
    - "**/*.lock"
    - "**/*.json"
    - "**/*.js"
    - "**/*.hcl"